# requiring the environment of NodeJS 4.2.2
image: node:8.9.4

# add 'node_modules' to cache for speeding up builds
cache:
  paths: 
    - node_modules/ # Node modules and dependencies

before_script:
  - npm install gitbook-cli -g # install gitbook
  - gitbook fetch latest # fetch latest stable version

# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  script:
    - gitbook build . public
  artifacts:
    paths:
      - public
  only:
    - pages # this job will affect only the 'pages' branch

